---
title: "A549_SARS-CoV-2"
author: "Meiyue Wang"
date: "2026-05-05"
output: html_document
---

1.read data
```{r}
data <- read.csv("data/raw/GSE147507_RawReadCounts_Human.tsv",
                 header = TRUE,
                 sep = "\t",
                 row.names = 1,
                 check.names = FALSE)
data
```
2.select samples
```{r}
selected_sample_names <- colnames(data)[
  grepl("Series2_A549",colnames(data)) &
    (grepl("Mock",colnames(data)) |
    grepl("SARS-CoV-2",colnames(data)))]
selected_sample_names
```
```{r}
selected_data <- data[,selected_sample_names]
selected_data
```
3.create a sample metadata table
```{r}
condition <- ifelse(
  grepl("Mock", selected_sample_names),
  "control",
  "infected"
)

coldata <- data.frame(
  row.names = colnames(selected_data),
  condition = factor(condition, levels = c("control","infected"))
)
coldata 
```
4. Filter low expression genes
```{r}
library(edgeR)

cpm_data <- cpm(selected_data) ## 把原始的counts转换成每一百万reads的表达量
head(cpm_data)
keep <- rowSums(cpm_data>1)>=2 ## 建立删选条件，输出的为逻辑矩阵
deep_filtered_data <- selected_data[keep,]
deep_filtered_data
```
5. DEseq2 
```{r}
dds <- DESeqDataSetFromMatrix(
  countData = deep_filtered_data,
  colData = coldata,
  design = ~ condition 
) ## 创建数据对象
dds <- DESeq(dds) ## 运行差异分析，自动完成normalization,dispersion，拟合模型以及统计检测
res <- results(dds) ## 提取结果
res
```
6. Remove genes containing NA
```{r}
res <- res[!is.na(res$padj),]
res
```
7. Convert DESeq2 results to a data.frame
```{r}
res_def <- as.data.frame(res)
summary(res_def)
```
8.Annotate genes
```{r}
res_def$significance <- "Not sig"
res_def$significance[res_def$padj<0.05&res$log2FoldChange>1] <- "Up"
res_def$significance[res_def$padj<0.05&res$log2FoldChange< -1] <- "Down"

table(res_def$significance)
```
9. Visualization-Volcano plot
```{r}
#pdf("volcano_plot_A549_SARS-CoV-2.pdf",width = 6,height = 5)
library(ggplot2)
ggplot(res_def,aes(x = log2FoldChange,y = -log10(padj))) +
  geom_point(aes(color = significance), alpha = 0.6, size = 1.5) + 
  scale_color_manual(values = c("Up" = "red", "Down" = "blue", "Not sig" = "grey")) +
  geom_vline(xintercept = c(-1,1),linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05),linetype = "dashed") +
  labs(title = "Volcano plot: SARS-CoV-2 vs Control (A549)",
       x = "log2 Fold Change",
       y = "-log10 adjusted p-value") +
  theme_minimal()
#dev.off()
```
10. Differential expressed gene table
```{r}
up_regulated_genes <- res_def[res_def$significance  ==  "Up",]

up_regulated_genes <- up_regulated_genes[order(-up_regulated_genes$log2FoldChange), ]

up_regulated_genes

write.csv(up_regulated_genes, 
          file = "A549_SARS-CoV-2_Mock_up_regulated_genes.csv", 
          row.names = TRUE)
```
```{r}
down_regulated_genes <- res_def[res_def$significance == "Down",]

down_regulated_genes <- down_regulated_genes[order(down_regulated_genes$log2FoldChange), ]

down_regulated_genes

write.csv(down_regulated_genes, 
          file = "A549_SARS-CoV-2_Mock_down_regulated_genes.csv", 
          row.names = TRUE)
```
11. Heatmap
```{r}
library(DESeq2) #做vst转换
library(ComplexHeatmap) #画高级热图
library(circlize) #设置颜色梯度
library(dendextend) #旋转聚类数

# 1. 提取差异基因
up_genes <- rownames(res_def[res_def$significance == "Up", ]) #提取上调基因
down_genes <- rownames(res_def[res_def$significance == "Down", ]) #提取下调基因
gene_list <- c(up_genes, down_genes) #合并成热图要展示的基因列表

# 2. VST variance stabilizing transformation,raw， VST 是让不同基因之间“方差可比”，而 Z-score 是让每个基因的“表达模式可比较”。 counts越大，方差越大，直接做图，高表达基因会主导图形，所以需要先做转化让不同表达水平的基因方差更稳定
vsd <- vst(dds, blind = FALSE) #把raw counts转换成适合画热图的表达量
mat <- assay(vsd)[gene_list, ] #只提取差异基因对应的表达矩阵

# 3. Z-score
mat_z <- t(scale(t(mat))) #查看每个基因在不同样本中相对高低，而不是绝对表达量大小，t代表transpose，意思是行列互换，将基因变成列，因为scale默认是按照列操作，所以scale(t(mat))是在对每个基因做标准化，计算z-score（Z = (x - mean) / sd），即基因在每个样本中表达的相对高低，而不是绝对表达量，计算完之后再进行行列转换
mat_z <- mat_z[complete.cases(mat_z), ] #complete.cases(mat_z)表示每一行是否有na，返回逻辑向量，[ , ]代表取子集，只保留true的行。complete.cases() 用来删除含有 NA 的行，这些 NA 通常来自标准差为 0 的基因（没有表达变化）。

# 4. 样本信息
sample_info <- as.data.frame(colData(dds)) #dds是DESeq2 对象，里面包含：count 矩阵，样本信息（metadata）和实验设计，colData(dds) 就是：每个样本的注释信息
sample_info$sample <- rownames(sample_info) #新建一列叫sample
sample_info$condition <- factor(sample_info$condition,
                                levels = c("control", "infected"))

# 5. 先定义你想要的最终列顺序
target_order <- c(
  sample_info$sample[sample_info$condition == "control"],
  sample_info$sample[sample_info$condition == "infected"]
)

# 6. 对列做聚类（所有样本一起）
hc <- hclust(dist(t(mat_z)))
dend <- as.dendrogram(hc)

# 7. 旋转树，让 control 在左、infected 在右
dend <- rotate(dend, order = target_order)

# 8. 列注释
ha_col <- HeatmapAnnotation(
  condition = sample_info$condition[match(colnames(mat_z), sample_info$sample)],
  col = list(condition = c("control" = "#00BFC4",
                           "infected" = "#F8766D"))
)

# 9. 颜色
col_fun <- colorRamp2(c(-2, 0, 2), c("#3B73B9", "white", "#D7301F"))

# 10. 导出 PDF
pdf("heatmap_A549.pdf", width = 8, height = 12)

Heatmap(
  mat_z,
  name = "Z-score",
  top_annotation = ha_col,
  col = col_fun,
  cluster_rows = FALSE,
  cluster_columns = dend,   # 直接传入旋转后的总树
  show_row_names = TRUE,
  show_column_names = TRUE,
  row_names_gp = gpar(fontsize = 6),
  column_names_gp = gpar(fontsize = 10),
  column_title = "Differentially expressed genes in A549 cells after SARS-CoV-2 infection"
)

dev.off()
```
12.PCA
```{r}
library(DESeq2)
vsd <- vst(dds, blind = TRUE) ## dds <- DESeqDataSetFromMatrix(...) 👉 里面包含：raw counts，sample信息和设计（condition）

pca <- prcomp(t(assay(vsd)))

#pdf("PCA_NHBE_SARS-CoV-2.pdf",width = 5,height = 5)

group <- c("control","control","control","infected","infected","infected")
cols <- ifelse(group == "control", "grey50", "orange")

plot(
  pca$x[,1], pca$x[,2],
  col = cols,
  pch = 19,
  cex = 1.5,
  xlim = c(-20, 20),
  ylim = c(-15, 15),  # ⭐扩大PC2显示范围
  
  xlab = paste0("PC1 (", round(100 * summary(pca)$importance[2,1], 1), "%)"),
  ylab = paste0("PC2 (", round(100 * summary(pca)$importance[2,2], 1), "%)"),
  main = "PCA of A549_SARS-CoV-2/Mock"
)
sample_names <- c(
  "M1","M2","M3",
  "C1","C2","C3"
)
text(
  pca$x[,1], pca$x[,2],
  labels = sample_names,
  pos = 3,
  cex = 0.9
)
#dev.off()
```
13. Go（gene ontology）analysis
```{r}
library(clusterProfiler) ## 加载分析工具，可以用来做GO,KEGG,GSEA
library(org.Hs.eg.db)  ## 加载人类基因注释数据库,包含人类基因信息，基因id对应关系以及go注释
up_gene_list <- rownames(up_regulated_genes)
up_gene <- bitr( ##把基因ID从一种格式转换成另一种
  up_gene_list,  ##输入的基因列表
  fromType = "SYMBOL", ##当前id类型
  toType = "ENTREZID", ##转换成的id 类型
  OrgDb = org.Hs.eg.db ##使用的人类数据库
)
head(up_gene,20) ##查看前20行结果
dim(up_gene) ##查看数据维度
gene_entrez <- unique(as.character(up_gene$ENTREZID))
ego <- enrichGO(
  gene = gene_entrez,
  OrgDb = org.Hs.eg.db,
  keyType = "ENTREZID",
  ont = "BP",   ##Biological Process,MF molecular function, CC cellular component
  pAdjustMethod = "BH", ## benjamini-hochberg，多重检验矫正方法
  pvalueCutoff = 0.05,
  readable = TRUE ##把结果从ENTREZID转回基因名
)
head(ego) ##默认显示前6条
dim(ego)
#pdf("barplot_A549_SARS-CoV-2.pdf",width = 5,height = 6)
#pdf("dotplot_A549_SARS-CoV-2.pdf",width = 5,height = 4)
barplot(ego, showCategory = 10, font.size = 8)
dotplot(ego, showCategory = 10, font.size = 8)
#dev.off()

```
14. KEGG analysis
```{r}
#pdf("barplot_A549_SARS-CoV-2.pdf",width = 5,height = 6)
#pdf("dotplot_A549_SARS-CoV-2.pdf",width = 5,height = 4)
ekegg <- enrichKEGG(
  gene = gene_entrez,
  organism = "hsa",       # hsa = human
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH"
)
ekegg
head(ekegg)
dim(ekegg)
barplot(ekegg, showCategory = 10,font.size = 8)
dotplot(ekegg, showCategory = 10,font.size = 8)
#dev.off()
```
15.GSEA analysis
```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
res_df$SYMBOL <- rownames(res_df)

gene_df <- bitr(
  res_df$SYMBOL,
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Hs.eg.db
)
res_merge <- merge(res_df, gene_df, by = "SYMBOL")
geneList <- res_merge$log2FoldChange
names(geneList) <- res_merge$ENTREZID

geneList <- sort(geneList, decreasing = TRUE)
gsea_kegg <- gseKEGG(
  geneList = geneList,
  organism = "hsa",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  verbose = FALSE
)
library(enrichplot)
library(ggplot2)
#pdf("gseaplot2_A549_SARS-CoV-2.pdf",width = 6,height = 4)
gseaplot2(gsea_kegg, geneSetID = 1) 

#dev.off()
as.data.frame(gsea_kegg)
head(gsea_kegg@result)
```


check ACE2 expression
```{r}
data["ACE2", selected_sample_names]
```

