---
title: "NHBE_SARS-CoV-2"
author: "Meiyue Wang"
date: "2026-05-05"
output: html_document
---

1. Read data
```{r}
data <- read.table("data/raw/GSE147507_RawReadCounts_Human.tsv",
                   header = TRUE,
                   sep = "\t",
                   row.names = 1,
                   check.names = FALSE)
data
```
2. Select samples
```{r}
selected_sample_names <- colnames(data)[grepl("Series1_NHBE",colnames(data))
                                        & (grepl("Mock",colnames(data)) |
                                             grepl("SARS-CoV-2",colnames(data))
                                           )]
selected_sample_names
```

```{r}
selected_data <- data[,selected_sample_names]
selected_data
```
3. Create a sample metadata table
```{r}
condition <- ifelse(
  grepl("Mock", selected_sample_names), #如果样品名里包含 "Mock" → control，否则 → infected
  "control",
  "infected"
)

coldata <- data.frame(
  row.names = colnames(selected_data),
  condition = factor(condition, levels = c("control","infected"))
)
coldata
```
4. Filter low expression genes
```{r}
library(edgeR)

cpm_data <- cpm(selected_data) ## 把原始的counts转换成每一百万reads的表达量
head(cpm_data)
keep <- rowSums(cpm_data>1)>=2 ## 建立删选条件，输出的为逻辑矩阵
deep_filtered_data <- selected_data[keep,]
deep_filtered_data
```
5. DEseq2 
```{r}
dds <- DESeqDataSetFromMatrix(
  countData = deep_filtered_data,
  colData = coldata,
  design = ~ condition 
) ## 创建数据对象
dds <- DESeq(dds) ## 运行差异分析，自动完成normalization,dispersion，拟合模型以及统计检测
res <- results(dds) ## 提取结果
res
```
6. Remove genes containing NA
```{r}
res <- res[!is.na(res$padj),]
res
```
7. Convert DESeq2 results to a data.frame
```{r}
res_def <- as.data.frame(res)
summary(res_def)
```
8.Annotate genes
```{r}
res_def$significance <- "Not sig"
res_def$significance[res_def$padj<0.05&res$log2FoldChange>1] <- "Up"
res_def$significance[res_def$padj<0.05&res$log2FoldChange< -1] <- "Down"

table(res_def$significance)
```

9. Visualization-Volcano plot
```{r}
#pdf("volcano_plot_NHEB_SARS-CoV-2.pdf",width = 6,height = 5)
library(ggplot2)
ggplot(res_def,aes(x = log2FoldChange,y = -log10(padj))) +
  geom_point(aes(color = significance), alpha = 0.6, size = 1.5) + 
  scale_color_manual(values = c("Up" = "red", "Down" = "blue", "Not sig" = "grey")) +
  geom_vline(xintercept = c(-1,1),linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05),linetype = "dashed") +
  labs(title = "Volcano plot: SARS-CoV-2 vs Control (NHBE)",
       x = "log2 Fold Change",
       y = "-log10 adjusted p-value") +
  theme_minimal()
#dev.off()
```
10. Differential expressed gene table
```{r}
up_regulated_genes <- res_def[res_def$significance  ==  "Up",]

up_regulated_genes <- up_regulated_genes[order(-up_regulated_genes$log2FoldChange), ]

up_regulated_genes

write.csv(up_regulated_genes, 
          file = "NHEB_SARS-CoV-2_Mock_up_regulated_genes.csv", 
          row.names = TRUE)
```

```{r}
down_regulated_genes <- res_def[res_def$significance == "Down",]

down_regulated_genes <- down_regulated_genes[order(down_regulated_genes$log2FoldChange), ]

down_regulated_genes

write.csv(down_regulated_genes, 
          file = "NHEB_SARS-CoV-2_Mock_down_regulated_genes.csv", 
          row.names = TRUE)
```

11. Heatmap
```{r}
library(DESeq2) #做vst转换
library(ComplexHeatmap) #画高级热图
library(circlize) #设置颜色梯度
library(dendextend) #旋转聚类数

# 1. 提取差异基因
up_genes <- rownames(res_def[res_def$significance == "Up", ]) #提取上调基因
down_genes <- rownames(res_def[res_def$significance == "Down", ]) #提取下调基因
gene_list <- c(up_genes, down_genes) #合并成热图要展示的基因列表

# 2. VST variance stabilizing transformation,raw， VST 是让不同基因之间“方差可比”，而 Z-score 是让每个基因的“表达模式可比较”。 counts越大，方差越大，直接做图，高表达基因会主导图形，所以需要先做转化让不同表达水平的基因方差更稳定
vsd <- vst(dds, blind = FALSE) #把raw counts转换成适合画热图的表达量
mat <- assay(vsd)[gene_list, ] #只提取差异基因对应的表达矩阵

# 3. Z-score
mat_z <- t(scale(t(mat))) #查看每个基因在不同样本中相对高低，而不是绝对表达量大小，t代表transpose，意思是行列互换，将基因变成列，因为scale默认是按照列操作，所以scale(t(mat))是在对每个基因做标准化，计算z-score（Z = (x - mean) / sd），即基因在每个样本中表达的相对高低，而不是绝对表达量，计算完之后再进行行列转换
mat_z <- mat_z[complete.cases(mat_z), ] #complete.cases(mat_z)表示每一行是否有na，返回逻辑向量，[ , ]代表取子集，只保留true的行。complete.cases() 用来删除含有 NA 的行，这些 NA 通常来自标准差为 0 的基因（没有表达变化）。

# 4. 样本信息
sample_info <- as.data.frame(colData(dds)) #dds是DESeq2 对象，里面包含：count 矩阵，样本信息（metadata）和实验设计，colData(dds) 就是：每个样本的注释信息
sample_info$sample <- rownames(sample_info) #新建一列叫sample
sample_info$condition <- factor(sample_info$condition, #强制定义顺序：control 在前，infected 在后
                                levels = c("control", "infected"))

# 5. 先定义你想要的最终列顺序
target_order <- c(
  sample_info$sample[sample_info$condition == "control"],
  sample_info$sample[sample_info$condition == "infected"]
)

# 6. 对列做聚类（所有样本一起）
hc <- hclust(dist(t(mat_z))) #转换行列，然后dist()计算样本之间的距离，dist() 总是按“行”算距离 → 想算列，就必须先 t()，hclust() = 层次聚类（hierarchical clustering），把样本按照“相似性”分组，并生成一棵树（dendrogram）
dend <- as.dendrogram(hc) #把聚类结果hc转换成树状图对象

# 7. 旋转树，让 control 在左、infected 在右
dend <- rotate(dend, order = target_order)

# 8. 列注释
ha_col <- HeatmapAnnotation(
  condition = sample_info$condition[match(colnames(mat_z), sample_info$sample)],#按照 mat_z 的列名顺序，去 sample_info 里找到对应的 condition
  col = list(condition = c("control" = "#00BFC4",
                           "infected" = "#F8766D"))
)

# 9. 颜色
col_fun <- colorRamp2(c(-2, 0, 2), c("#3B73B9", "white", "#D7301F")) #颜色函数：colorRamp2

# 10. 导出 PDF
#pdf("heatmap_control_left_with_global_dendrogram.pdf", width = 8, height = 12)

Heatmap(
  mat_z, #真正要画热图的矩阵
  name = "Z-score", #heatmap 右边会出现颜色图例，标题就是：Z-score
  top_annotation = ha_col, #把你前面做好的分组注释放到 heatmap 顶部
  col = col_fun, #使用定义的颜色方案
  cluster_rows = TRUE, #不对基因重新聚类
  cluster_columns = dend,   # 直接传入旋转后的总树
  show_row_names = TRUE, #显示基因名
  show_column_names = TRUE, #显示样本名
  row_names_gp = gpar(fontsize = 6), #控制基因名字体大小
  column_names_gp = gpar(fontsize = 10), #控制样本名字体大小
  column_title = "Differentially expressed genes in NHBE cells after SARS-CoV-2 infection"
) #给 heatmap 加标题

#dev.off()
```
12.PCA
```{r}
library(DESeq2)
vsd <- vst(dds, blind = TRUE) ## dds <- DESeqDataSetFromMatrix(...) 👉 里面包含：raw counts，sample信息和设计（condition）， blind = TRUE，不使用实验设计信息（condition）适合：无偏地看样本整体结构

pca <- prcomp(t(assay(vsd))) #assay(vsd) 提取表达矩阵：行 = gene；列 = sample；t(...) 转置：行 = sample；列 = gene 因为 PCA 要：每一行 = 一个样本，prcomp(...)做 PCA 分析：把高维数据（很多基因）压缩成几个主成分（PC1, PC2...）

#pdf("PCA_NHBE_SARS-CoV-2.pdf",width = 5,height = 5)

group <- c("control","control","control","infected","infected","infected")
cols <- ifelse(group == "control", "grey50", "orange") #if是control组，灰色；否则是橘色

plot(
  pca$x[,1], pca$x[,2],
  col = cols,
  pch = 19, #实心圆
  cex = 1.5, #点大小
  xlim = c(-20, 15), #坐标的范围
  ylim = c(-15, 15),  # 扩大PC2显示范围
  
  xlab = paste0("PC1 (", round(100 * summary(pca)$importance[2,1], 1), "%)"), #给横轴和纵轴加标签，summary(pca)$importance 会返回每个主成分的信息，     PC1    PC2    PC3
#Standard deviation          ...
#Proportion of Variance      0.62   0.18   0.09
#Cumulative Proportion       0.62   0.80   0.89
#[2,1]代表第二行第一列
#100 *变成百分比
#round(..., 1)代表保留 1 位小数。
#paste0(...)代表把文字拼起来。如果summary(pca)$importance[2,1] = 0.623，那么paste0("PC1 (", round(100 * 0.623, 1), "%)")，结果就是PC1 (62.3%)
  ylab = paste0("PC2 (", round(100 * summary(pca)$importance[2,2], 1), "%)"),
  main = "PCA of NHBE_SARS-CoV-2/Mock" #标题
)
sample_names <- c(  #给每个点加一个名字
  "M1","M2","M3",
  "C1","C2","C3"
)
text(
  pca$x[,1], pca$x[,2],
  labels = sample_names,
  pos = 3, #在点上方加标签
  cex = 0.9 #标签字体的大小
)
#dev.off()
```

13. Go（gene ontology）analysis
```{r}
library(clusterProfiler) ## 加载分析工具，可以用来做GO,KEGG,GSEA
library(org.Hs.eg.db)  ## 加载人类基因注释数据库,包含人类基因信息，基因id对应关系以及go注释
up_gene_list <- rownames(up_regulated_genes)
up_gene <- bitr( ##把基因ID从一种格式转换成另一种
  up_gene_list,  ##输入的基因列表
  fromType = "SYMBOL", ##当前id类型
  toType = "ENTREZID", ##转换成的id 类型
  OrgDb = org.Hs.eg.db ##使用的人类数据库
)
head(up_gene,20) ##查看前20行结果
dim(up_gene) ##查看数据维度
gene_entrez <- unique(as.character(up_gene$ENTREZID)) #从 up_gene 数据里提取 ENTREZ ID，转成字符（clusterProfiler 要求），去重（unique()
ego <- enrichGO(
  gene = gene_entrez, #输入的基因列表
  OrgDb = org.Hs.eg.db, #人类基因注释数据库
  keyType = "ENTREZID", #你的基因ID是ENTREZ ID
  ont = "BP",   ##Biological Process,MF molecular function, CC cellular component
  pAdjustMethod = "BH", ## benjamini-hochberg，多重检验矫正方法
  pvalueCutoff = 0.05,
  readable = TRUE ##把结果从ENTREZID转回基因名
)
head(ego) ##默认显示前6条
dim(ego)
#pdf("barplot_NHEB_SARS-CoV-2.pdf",width = 5,height = 6)
#pdf("dotplot_NHEB_SARS-CoV-2.pdf",width = 5,height = 4)
barplot(ego, showCategory = 10, font.size = 8) #显示最显著的10个GO term
dotplot(ego, showCategory = 10, font.size = 8)
#dev.off()

```
14. KEGG analysis
```{r}
#pdf("barplot_NHEB_SARS-CoV-2.pdf",width = 5,height = 6)
#pdf("dotplot_NHEB_SARS-CoV-2.pdf",width = 5,height = 4)
ekegg <- enrichKEGG(
  gene = gene_entrez,
  organism = "hsa",       # hsa = human
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH"
)
ekegg
head(ekegg)
dim(ekegg)
barplot(ekegg, showCategory = 10,font.size = 8)
dotplot(ekegg, showCategory = 10,font.size = 8)
#dev.off()
```
15.GSEA analysis
```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
res_df$SYMBOL <- rownames(res_df) #把 res_df 的行名，也就是基因名，保存成一列 SYMBOL。

gene_df <- bitr(
  res_df$SYMBOL,
  fromType = "SYMBOL",
  toType = "ENTREZID",
  OrgDb = org.Hs.eg.db
) #bitr() 是 ID 转换函数。这里是把：SYMBOL → ENTREZID
res_merge <- merge(res_df, gene_df, by = "SYMBOL") #把 DESeq2 的结果和 ENTREZID 对应表合并，SYMBOL是匹配依据，按照SYMBOL这一列进行匹配，merge() 默认只保留两个表中都能匹配上的基因。
geneList <- res_merge$log2FoldChange
names(geneList) <- res_merge$ENTREZID

geneList <- sort(geneList, decreasing = TRUE) #按 log2FC 从高到低排序
gsea_kegg <- gseKEGG(
  geneList = geneList,
  organism = "hsa",
  pvalueCutoff = 0.05,
  pAdjustMethod = "BH",
  verbose = FALSE #不显示运行过程的信息
)
library(enrichplot)
library(ggplot2)
#pdf("gseaplot2_NHBE_SARS-CoV-2.pdf",width = 6,height = 4)
gseaplot2(gsea_kegg, geneSetID = 1) #geneSetID = 1 表示画结果表里的第 1 个通路。

#dev.off()
as.data.frame(gsea_kegg)
head(gsea_kegg@result)
```

